### ISSUE TITLE
Contianer Failing

### ISSUE THREAD

**Issue by fatherlinux** [jose-delarosa/docker-images#1] opened 2015-08-03 20:12 UTC
I can build and start the container OK, but then when I go to execute the "exec" command, it fails in a strange way. Any ideas?

[root@rhel7 ~]# docker ps
CONTAINER ID        IMAGE                  COMMAND                CREATED             STATUS                         PORTS                    NAMES
bcb94a1234e9        openmanage8.1:latest   "/bin/sh -c 'srvadmi   2 minutes ago       Restarting (1) 3 seconds ago   0.0.0.0:1311->1311/tcp   omsa81         

[root@rhel7 ~]# docker exec omsa81 omreport system summary
Cannot run exec command a1c8c20c4e161fa3584ef470f7d4516dd0cd3c068a3290ef24dca44be3a3bd41 in container bcb94a1234e9a5ccc54e949700cb2ebcaad0fa7906fe38140780015b97d489fd: No active container exists with ID bcb94a1234e9a5ccc54e949700cb2ebcaad0fa7906fe38140780015b97d489fd
Error starting exec command in container a1c8c20c4e161fa3584ef470f7d4516dd0cd3c068a3290ef24dca44be3a3bd41: Cannot run exec command a1c8c20c4e161fa3584ef470f7d4516dd0cd3c068a3290ef24dca44be3a3bd41 in container bcb94a1234e9a5ccc54e949700cb2ebcaad0fa7906fe38140780015b97d489fd: No active container exists with ID bcb94a1234e9a5ccc54e949700cb2ebcaad0fa7906fe38140780015b97d489fd

**Comment by jose-delarosa** [comment] 2015-08-03 21:04
I just downloaded it and verified and didn't have an issue. Can you send me the image ID of your image to make sure you are running the right one or that it's not corrupt?

```
 REPOSITORY                             TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
 docker.io/jdelaros1/openmanage         latest              e513051486ea        3 days ago          927.2 MB
```

Also, please pull the _openmanage:latest_ image, not _openmanage:8.1_.

**Comment by jose-delarosa** [comment] 2015-08-03 21:05
One more thing, it's a bit hard reading the command output the way you pasted it, try using Markdown: https://guides.github.com/features/mastering-markdown/.

**Comment by fatherlinux** [comment] 2015-08-03 21:16
Sorry, originally, I was trying to build myself, but now I am pulling your image and getting the same thing. I am running this from a rhel7.1 image.

I am running the docker command like so:

```
docker run --privileged -d -p 1311:1311 --restart=always    -v /lib/modules/`uname -r`:/lib/modules/`uname -r`   --name=omsa81 docker.io/jdelaros1/openmanag
```

Then, here is the output of the 'docker ps'

```
[root@rhel7 ~]# docker ps
CONTAINER ID        IMAGE                                   COMMAND                CREATED              STATUS                          PORTS                    NAMES
bee9b97ae585        docker.io/jdelaros1/openmanage:latest   "/bin/sh -c 'srvadmi   About a minute ago   Restarting (1) 21 seconds ago   0.0.0.0:1311->1311/tcp   omsa81
```

Finally, here is the output of the exec command:

```
[root@rhel7 ~]# docker exec omsa81 omreport system summary
Cannot run exec command 12f3e90af6a87c97e0de41881eaef2b3dc008f512042d8878438e65a93894e60 in container bee9b97ae585dae472b627964328a42a2346798e6531452ac2bc1a1ac0288657: No active container exists with ID bee9b97ae585dae472b627964328a42a2346798e6531452ac2bc1a1ac0288657
Error starting exec command in container 12f3e90af6a87c97e0de41881eaef2b3dc008f512042d8878438e65a93894e60: Cannot run exec command 12f3e90af6a87c97e0de41881eaef2b3dc008f512042d8878438e65a93894e60 in container bee9b97ae585dae472b627964328a42a2346798e6531452ac2bc1a1ac0288657: No active container exists with ID bee9b97ae585dae472b627964328a42a2346798e6531452ac2bc1a1ac0288657
```

Stranger than all of this, it worked once when I first built from the Dockerfile. Then it hasn't worked again. 

Finally, my apologies, the whole reason I was playing with any of this was to try and add a RUN label to make this easier to run with the "atomic" command:

```
# Use CentOS 7 base image from Docker Hub
FROM centos:centos7
MAINTAINER Jose De la Rosa "https://github.com/jose-delarosa" 

# Do overall update and install missing packages needed for OpenManage
RUN yum -y update
RUN yum -y install gcc wget perl passwd which tar
RUN yum -y install libstdc++.so.6 compat-libstdc++-33.i686 glibc.i686

# Set login credentials
RUN echo 'root:password' | chpasswd

# Define OMSA repo
RUN wget -q -O - http://linux.dell.com/repo/hardware/latest/bootstrap.cgi | bash

# Install all but we could select specific components to reduce image size
RUN yum -y install srvadmin-all

# Clean cache to minimize container image
RUN yum clean all

# Add to PATH
ENV PATH $PATH:/opt/dell/srvadmin/bin:/opt/dell/srvadmin/sbin

# Labels
LABEL RUN="docker run --privileged -d -p 1311:1311 --restart=always -v /lib/modules/`uname -r`:/lib/modules/`uname -r` --name=omsa81 --label IMAGE IMAGE"

# Restart application to ensure a clean start
CMD srvadmin-services.sh restart && tail -f /opt/dell/srvadmin/var/log/openmanage/dcsys64.xml
```

**Comment by jose-delarosa** [comment] 2015-08-03 22:21
Fatherlinux: I updated the README.md file in github which in turn triggered a rebuild of the image (annoying since I didn't update the Dockefile). Anyway, I downloaded the image on 4 different servers (2 x RHEL 7.1 and 2 x Ubuntu 14.04) and didn't see any issues. The latest image ID is _c5f9045b5182_.

However, if you use the Dockerfile, you should be able to build your own image (perfectly fine option). I can't tell why you are having issues. Have you build other container images on the same RHEL 7 host?

**Comment by jose-delarosa** [comment] 2015-11-19 02:41
Closing. Unable to reproduce. Try latest Dockerfile please.

**Closed as completed by jose-delarosa** 2015-11-19 02:41 UTC

**Comment by fatherlinux** [comment] 2015-11-20 05:03
I just tried this on a fresh RHEL 7.2 box with Docker 1.8.2

```[root@rhel7 openmanage81]# docker run --privileged -d -p 1311:1311 --restart=always    -v /lib/modules/`uname -r`:/lib/modules/`uname -r`   --name=omsa81 docker.io/jdelaros1/openmanage
Unable to find image 'docker.io/jdelaros1/openmanage:latest' locally
Trying to pull repository docker.io/jdelaros1/openmanage ... latest: Pulling from jdelaros1/openmanage
47d44cb6f252: Pull complete 
168a69b62202: Pull complete 
812e9d9d677f: Pull complete 
4234bfdd88f8: Pull complete 
ce20c473cd8a: Pull complete 
925799d56e7b: Pull complete 
5ad274880b51: Pull complete 
0efd3dfde6f8: Pull complete 
db6e1ef3ae7f: Pull complete 
401810108e79: Pull complete 
0def114e7770: Pull complete 
821e0c0b94f6: Pull complete 
7eb843be7b60: Pull complete 
7ff9273ec632: Pull complete 
Digest: sha256:3f5981805d49476bccf193617d51d5a3374781ddb897841c1d703fb2e98a27b0
Status: Downloaded newer image for docker.io/jdelaros1/openmanage:latest

2b96bb7ed87168e16164baab5515d719af2e92dde98487ab30629182eee6a1b1
[root@rhel7 openmanage81]# docker exec omsa81 omreport system summary
[root@rhel7 openmanage81]# docker exec omsa81 omreport system summary
[root@rhel7 openmanage81]# docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED              STATUS                          PORTS                    NAMES
2b96bb7ed871        docker.io/jdelaros1/openmanage   "/bin/sh -c 'srvadmin"   About a minute ago   Restarting (1) 20 seconds ago   0.0.0.0:1311->1311/tcp   omsa81
[root@rhel7 openmanage81]# docker exec omsa81 omreport system summary
System Summary

---

## Software Profile

Systems Management
Name            : Dell OpenManage Server Administrator
Version         : 8.1.0
Description     : Systems Management Software
Contains        : A library for parsing GNU style command line arguments 8.1.0
                : Apache Tomcat Webserver 7.0.57
                : Data Engine 8.1.0
                : Data Engine SNMP 8.1.0
                : Disney SNMP 8.1.0
                : Hardware Abstraction Programming Interface 8.1.0
                : Instrumentation Services 8.1.0
                : Integrated Tunnel Provider 1.3.0
                : Meta package for installing all Server Administrator features 8.1.0
                : Meta package for installing the Server Administrator Storage Services feature 8.1.0
                : Meta package for installing the Server Administrator Web Server feature 8.1.0
                : Meta package for installing the Server Administrator cli component 8.1.0
                : Meta package for installing the Server Administrator snmp component 8.1.0
                : Meta package for installing the Server Administrator storage cli component 8.1.0
                : Meta package for installing the Server Administrator storage snmp component 8.1.0
                : Meta package for installing the Server Agent 8.1.0
                : Meta package for installing the Standard Server Agent 8.1.0
                : Meta rpm for RAC4 components 7.1.0
                : Meta rpm for RAC5 components 8.1.0
                : Meta rpm for iDRAC components 8.1.0
                : Modular Server Virtual Media CLI Utils 1.0.0
                : Monolithic Server Virtual Media CLI Utils 1.0.0
                : NVMe Library 8.1.0
                : OSLogging control 8.1.0
                : OpenManage Inventory Collector 8.1.0
                : Oracle Java Runtime Environment 1.7.0_72
                : RAC Command Interface 7.1.0
                : RAC Integration Layer 8.1.0
                : RAC5 Command Interface 7.1.0
                : RealSSD package for storage management 8.1.0
                : Remote Access Card Data Populator 7.1.0
                : Remote Access Card Data Populator 8.1.0
                : Remote Access Card Managed Node 7.1.0
                : Server Administrator CLI 8.1.0
                : Server Administrator Common Framework 8.1.0
                : Server Administrator Common Services 8.1.0
                : Server Administrator Core 8.1.0
                : Server Administrator XML Support SDK 8.1.0
                : Storage Management CLI component 5.0.1
                : Storage Management SNMP component 5.0.1
                : Storage Management System Utilities Package / Libsysfs 1.3.0
                : Storage Management accessors package 5.0.1
                : Storage Management common files for GUI and CLI 5.0.1
                : Storage Management package for GUI component 5.0.1
                : StoreLib package for storage management 8.1.0
                : System Utilities Package/Libsysfs for LSI storage libraries 2.1.0
                : iDRAC SNMP components 8.1.0
                : iDRAC6 Command Interface 8.1.0

---

## System

System
Host Name       : 2b96bb7ed871
System Location : 

[root@rhel7 openmanage81]# docker exec omsa81 omreport system summary
[root@rhel7 openmanage81]# docker exec omsa81 omreport system summary
[root@rhel7 openmanage81]# docker exec omsa81 omreport system summary
[root@rhel7 openmanage81]# docker exec omsa81 omreport system summary```

**Comment by fatherlinux** [comment] 2015-11-20 05:04
The first run didn't output anything, the second run did, then runs after that would output nothing...

**Comment by jose-delarosa** [comment] 2015-11-20 17:20
When starting the container, wait about 30 seconds for ALL services to start up. You can track with `docker logs -f omsa81`. I have been testing on about 10 servers this week, I made some changes, everything seems to work for me, including on RHEL 7.2 hosts. What PowerEdge server do you have?
